.gitignore, README.md, docs/README.md
Read the READMEs added for documentation guidelines
=> Adds documentation guidelines and adds docs to gitignore for local building

src/sensors/dr16.cpp, src/sensors/dr16.hpp
=> merge DR16 to main

.github/workflows/deploy-pages.yml
Github actions change to (hopefully) fix documentation generation. Will self-merge due to this being an actions change
=> Updates github actions checkout version

src/controls/state.cpp, src/controls/state.hpp, src/utils/timing.cpp, src/utils/timing.h
Update state class to include reference governor and have improved formatting. Also fix some formatting errors in timing.h
=> State & Reference Governor

Makefile
to make compilation of ref system stop yelling at me doing weird comment stuff for docs
=> Added -Wno-comment 

src/main.cpp, src/sensors/buff_encoder.cpp, src/sensors/buff_encoder.hpp
I copied the buff-encoder from the old testing code and made it into a class called BuffEncoder.
=> Feature buff encoder

src/sensors/ACS712.cpp, src/sensors/ACS712.hpp
The values it gives should be correct. They change according to power draw/usage, but I'm not sure its centered around the correct "zero".
=> Finished Current Sensor

src/controls/controller.hpp, src/controls/estimator.hpp, src/controls/estimator_manager.cpp, src/main.cpp, src/sensors/ACS712.cpp, src/sensors/ACS712.hpp, src/sensors/RefSystem.cpp, src/sensors/RefSystem.hpp
=> fixed ref issues

src/main.cpp, src/sensors/d200.cpp
Literally the easiest PR ever, I just added the lidar reads in the main loop
=> Read lidars in main

libraries/FlexCAN_T4/FlexCAN_T4.h, src/controls/controller.hpp, src/controls/estimator.hpp, src/sensors/IMUSensor.hpp
Fixes some virtual function declarations that cause linker errors on lower optimization levels (<-O1)
=> Patch inheritance fix

src/comms/config_layer.cpp, src/comms/config_layer.hpp, src/controls/controller.hpp, src/controls/controller_manager.cpp, src/controls/controller_manager.hpp, src/controls/estimator_manager.cpp, src/controls/estimator_manager.hpp, src/controls/state.cpp, src/controls/state.hpp, src/main.cpp
Reorganizes main into an inter-galactic function.
This prepares main and the controls stack for it's eventual re-factor while making main a bit easier to read.
=> Feature main reorganization

Makefile, src/utils/profiler.cpp, src/utils/profiler.hpp
Puts memory buffer in DMAMEM (ram 2) rather than flash.
=> Modified Profiler to store data in a sane place

tools/install_arduino.sh
=> Added curl dependency check

src/main.cpp, src/sensors/RefSystem.cpp, src/sensors/RefSystem.hpp
Cleans up reading/writing for ref system.
=> Patch vtm refactor

.gitignore, Makefile
Adds the generation of .dump and .map files in the build process.
=> Added build debug file generation

src/sensors/dr16.cpp
=> Fixes dr16 alignment issues

src/comms/config_layer.cpp
Found and fixed a very small error with the `CONFIG_OFF_ROBOT` macro found in config layer, as well as very slight reformatting to fit our style guidelines
=> Patch off robot macro

src/comms/SDManager.cpp, src/comms/config_layer.cpp, src/comms/config_layer.hpp, src/controls/estimator_manager.cpp, src/main.cpp, tools/monitor.sh
Implements hot reloading. This enables Teensy to be reconfigured after startup (say if Hive goes down and comes back up and wants to configure Teensy differently). 
This also has the nice side effect of making Hive resilient to Teensy crashes. Teensy can now die and come back to life and Hive still can maintain a connection with it. 
Teensy is also now resilient to Hive crashes, since Hive can go down and come back up, triggering another configure.
=> Feature hot reload

src/comms/ethernet_packet.hpp
Ups packet size from 4KB to 6KB
=> Patch ethernet size

src/main.cpp
Automatically triggers safety mode if our loop time is exceeded.
=> Patch slow loop freakout

.gitignore, Makefile, teensy4/imxrt1062_t41.ld, tools/install_compiler.sh
Upgrades our C++ version from 17 to 23
=> Added script to install arm gcc 14.2

Makefile, src/main.cpp, teensy4/CrashReport.cpp
Simple PR, just checks to see if a crash exists, and prints it forever.
=> Sends crash report over serial

src/controls/controller_manager.cpp, src/main.cpp, src/sensors/SensorManager.cpp, src/sensors/can/can_manager.hpp
This pr removes a lot of the status prints that slow down the teensy loop and cause weird controller behaviors.
=> tested no prints

src/comms/config_layer.cpp, src/controls/controller.cpp
Switch the or to an and so that it doesn't always wait 500 ms even if we got a 0 request from hive.
=> Fix infinite configure condition 

LICENSE
=> Updated license date range

.gitignore, Makefile, src/controls/estimator_manager.hpp, src/main.cpp
allows bear to create a compilation database for firmware by using "make cdb". Also gets rid of some unused includes in main that should have been in the previous pr
=> Oh god a bear
